package soundevent

import (
	"fmt"
	"math"
	"strings"
	"sync"
	"testing"
	"time"
)

func TestLogMelMatchesOfficialTensorFlowFrontend(t *testing.T) {
	waveform := make([]float32, WindowSamples)
	for i := range waveform {
		pcm := int32((uint64(i)*1103515245 + 12345) & 0xffff)
		waveform[i] = float32(pcm-32768) / 32768
	}
	got, err := LogMel(waveform)
	if err != nil {
		t.Fatal(err)
	}
	// Generated by the pinned official TensorFlow YAMNet features.py. These
	// cover both spectrum edges, populated bands, and different time frames.
	want := map[[2]int]float32{
		{0, 0}: -.16048661, {0, 10}: .8906344, {0, 63}: 3.262413,
		{17, 7}: .010544421, {47, 31}: 1.5497292, {95, 63}: 3.2635264,
	}
	for at, expected := range want {
		actual := got[at[0]*MelBands+at[1]]
		if diff := math.Abs(float64(actual - expected)); diff > 2e-4 {
			t.Errorf("feature[%d,%d]=%.7f, want %.7f (diff %.7g)", at[0], at[1], actual, expected, diff)
		}
	}
}

func testClassMap(t *testing.T) ClassMap {
	t.Helper()
	names := make([]string, ExpectedClasses)
	for i := range names {
		names[i] = fmt.Sprintf("class-%d", i)
	}
	for i, name := range targetNames {
		names[380+i] = name
	}
	var b strings.Builder
	b.WriteString("index,mid,display_name\n")
	for i, name := range names {
		fmt.Fprintf(&b, "%d,/m/%d,%q\n", i, i, name)
	}
	cm, err := ParseClassMap(strings.NewReader(b.String()))
	if err != nil {
		t.Fatal(err)
	}
	return cm
}

func TestClassMapValidatesNamesAndWidth(t *testing.T) {
	cm := testClassMap(t)
	if cm.Targets[ClassShatter] == 0 {
		t.Fatal("target name was not resolved")
	}
	if _, err := cm.Scores(make([]float32, ExpectedClasses-1)); err == nil {
		t.Fatal("wrong output width accepted")
	}
	var b strings.Builder
	b.WriteString("index,mid,display_name\n")
	for i, name := range cm.Names {
		if name == ClassSmokeAlarm {
			name = "Not the required class"
		}
		fmt.Fprintf(&b, "%d,/m/%d,%q\n", i, i, name)
	}
	if _, err := ParseClassMap(strings.NewReader(b.String())); err == nil {
		t.Fatal("class map missing a required target name was accepted")
	}
}

func TestCadenceDistinguishesT3AndT4(t *testing.T) {
	for n, want := range map[int]string{3: CadenceT3, 4: CadenceT4, 2: CadenceUnknown} {
		var c CadenceVerifier
		at := time.Unix(0, 0)
		c.Observe(false, at)
		for i := 0; i < n; i++ {
			at = at.Add(200 * time.Millisecond)
			c.Observe(true, at)
			at = at.Add(200 * time.Millisecond)
			c.Observe(false, at)
		}
		at = at.Add(1300 * time.Millisecond)
		if got := c.Observe(false, at); got != want {
			t.Errorf("%d bursts = %s, want %s", n, got, want)
		}
	}
}

func TestClassificationEvidenceRules(t *testing.T) {
	s := map[string]float32{ClassSmokeAlarm: .7}
	if k, _ := classify(s, .5, CadenceUnknown); k != KindSmokeAlarm {
		t.Fatalf("got %q", k)
	}
	s = map[string]float32{ClassShatter: .6, ClassGlass: .1, ClassCrack: .1}
	if k, _ := classify(s, .5, CadenceUnknown); k != "" {
		t.Fatalf("unsupported shatter became %q", k)
	}
	s[ClassShatter] = .9
	if k, _ := classify(s, .5, CadenceUnknown); k != "" {
		t.Fatalf("high shatter without glass/crack support became %q", k)
	}
	s[ClassGlass] = .3
	if k, _ := classify(s, .5, CadenceUnknown); k != KindGlassBreak {
		t.Fatalf("got %q", k)
	}
	s = map[string]float32{ClassSiren: .8}
	if k, _ := classify(s, .5, CadenceT4); k != KindPossibleCO {
		t.Fatalf("got %q", k)
	}
	if k, _ := classify(s, .5, CadenceT3); k != KindUnknown {
		t.Fatalf("got %q", k)
	}
}

type fakeInferer struct {
	mu     sync.Mutex
	inputs [][]float32
	out    []float32
	block  chan struct{}
}

func (f *fakeInferer) Infer(in []float32) ([]float32, error) {
	if f.block != nil {
		<-f.block
	}
	f.mu.Lock()
	f.inputs = append(f.inputs, append([]float32(nil), in...))
	f.mu.Unlock()
	return append([]float32(nil), f.out...), nil
}
func (f *fakeInferer) Close() error                 { return nil }
func (f *fakeInferer) Info() (string, string, bool) { return "test-runtime", "test-model", true }

func TestWindowOverlapAndS16Normalisation(t *testing.T) {
	inf := &fakeInferer{out: make([]float32, ExpectedClasses)}
	d, err := New(inf, testClassMap(t), Config{Mode: ModeShadow, Threshold: .5, Confirmations: 2, Cooldown: time.Second}, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer d.Close()
	// 24,000 sequential samples yields two windows: starts 0 and 7680.
	pcm := make([]byte, 24000*2)
	for i := 0; i < 24000; i++ {
		v := int16(i - 9000)
		pcm[2*i] = byte(v)
		pcm[2*i+1] = byte(uint16(v) >> 8)
	}
	for len(pcm) > 0 {
		n := 2560
		if n > len(pcm) {
			n = len(pcm)
		}
		d.PushBytesAt(pcm[:n], time.Now())
		pcm = pcm[n:]
		time.Sleep(time.Millisecond)
	}
	deadline := time.Now().Add(time.Second)
	for time.Now().Before(deadline) {
		inf.mu.Lock()
		n := len(inf.inputs)
		inf.mu.Unlock()
		if n >= 2 {
			break
		}
		time.Sleep(time.Millisecond)
	}
	inf.mu.Lock()
	defer inf.mu.Unlock()
	if len(inf.inputs) != 2 {
		t.Fatalf("windows=%d, want 2", len(inf.inputs))
	}
	want0 := float32(-9000) / 32768
	want1 := float32(7680-9000) / 32768
	if inf.inputs[0][0] != want0 || inf.inputs[1][0] != want1 {
		t.Fatalf("starts %.6f %.6f, want %.6f %.6f", inf.inputs[0][0], inf.inputs[1][0], want0, want1)
	}
}

func TestPlaybackRequiresStricterEvidence(t *testing.T) {
	cm := testClassMap(t)
	out := make([]float32, ExpectedClasses)
	out[cm.Targets[ClassSmokeAlarm]] = .6
	inf := &fakeInferer{out: out}
	events := make(chan Event, 1)
	d, _ := New(inf, cm, Config{Mode: ModeOn, Threshold: .5, Confirmations: 1, Cooldown: time.Second}, func() bool { return true }, func(e Event) { events <- e })
	defer d.Close()
	d.evaluate(map[string]float32{ClassSmokeAlarm: .6}, time.Now())
	select {
	case <-events:
		t.Fatal("playback candidate passed normal threshold")
	default:
	}
	d.evaluate(map[string]float32{ClassSmokeAlarm: .8}, time.Now())
	d.evaluate(map[string]float32{ClassSmokeAlarm: .8}, time.Now().Add(480*time.Millisecond))
	select {
	case e := <-events:
		if !e.Playback {
			t.Fatal("playback flag absent")
		}
	case <-time.After(time.Second):
		t.Fatal("strict playback event not emitted")
	}
}

func TestTemporalConfirmationAndCooldownCoalesceAnIncident(t *testing.T) {
	cm := testClassMap(t)
	inf := &fakeInferer{out: make([]float32, ExpectedClasses)}
	events := make(chan Event, 3)
	d, err := New(inf, cm, Config{
		Mode: ModeOn, Threshold: .5, Confirmations: 2, Cooldown: 10 * time.Second,
	}, nil, func(e Event) { events <- e })
	if err != nil {
		t.Fatal(err)
	}
	defer d.Close()
	scores := map[string]float32{ClassSmokeAlarm: .8}
	at := time.Unix(1000, 0)
	d.evaluate(scores, at)
	if len(events) != 0 {
		t.Fatal("one positive window emitted an event")
	}
	d.evaluate(scores, at.Add(480*time.Millisecond))
	if len(events) != 1 {
		t.Fatalf("two positive windows emitted %d events, want 1", len(events))
	}
	d.evaluate(scores, at.Add(960*time.Millisecond))
	d.evaluate(scores, at.Add(1440*time.Millisecond))
	if len(events) != 1 {
		t.Fatalf("continuous alarm escaped cooldown: %d events", len(events))
	}
	d.evaluate(scores, at.Add(11*time.Second))
	d.evaluate(scores, at.Add(11*time.Second+480*time.Millisecond))
	if len(events) != 2 {
		t.Fatalf("incident did not become eligible after cooldown: %d events", len(events))
	}
}

func TestMissingAssetsAreAnOrdinaryOpenError(t *testing.T) {
	t.Setenv("EM_SOUND_EVENT_DIR", t.TempDir())
	if d, err := Open(Config{Mode: ModeShadow}, nil, nil); err == nil {
		d.Close()
		t.Fatal("Open succeeded without runtime, model, or class map")
	}
}

func TestSequenceDoesNotResetWhenDetectorIsReplaced(t *testing.T) {
	cm := testClassMap(t)
	makeEvent := func() Event {
		events := make(chan Event, 1)
		d, err := New(&fakeInferer{out: make([]float32, ExpectedClasses)}, cm,
			Config{Mode: ModeShadow, Threshold: .5, Confirmations: 1}, nil,
			func(e Event) { events <- e })
		if err != nil {
			t.Fatal(err)
		}
		d.evaluate(map[string]float32{ClassSmokeAlarm: .8}, time.Now())
		d.Close()
		return <-events
	}
	first, second := makeEvent(), makeEvent()
	if second.Sequence <= first.Sequence {
		t.Fatalf("replacement reused or regressed event sequence: %d then %d",
			first.Sequence, second.Sequence)
	}
}

func TestQueueOverflowDropsWithoutBlocking(t *testing.T) {
	inf := &fakeInferer{out: make([]float32, ExpectedClasses), block: make(chan struct{})}
	d, _ := New(inf, testClassMap(t), Config{Mode: ModeShadow}, nil, nil)
	frame := make([]byte, 2560)
	start := time.Now()
	for i := 0; i < 100; i++ {
		d.PushBytesAt(frame, start)
	}
	if time.Since(start) > 100*time.Millisecond {
		t.Fatal("Push blocked")
	}
	if d.drops.Load() == 0 {
		t.Fatal("overflow was not counted")
	}
	close(inf.block)
	d.Close()
}

func TestCloseRacesWithPushSafely(t *testing.T) {
	d, _ := New(&fakeInferer{out: make([]float32, ExpectedClasses)}, testClassMap(t), Config{Mode: ModeShadow}, nil, nil)
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		for i := 0; i < 1000; i++ {
			d.PushBytesAt(make([]byte, 2560), time.Now())
		}
	}()
	d.Close()
	wg.Wait()
}
